export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAIL: "LOGOUT_FAIL",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_RAIL",
};

export const categoryConstants = {
  FETCH_ALL_CATEGORIES_REQUEST: "FETCH_ALL_CATEGORIES_REQUEST",
  FETCH_ALL_CATEGORIES_SUCCESS: "FETCH_ALL_CATEGORIES_SUCCESS",
  FETCH_ALL_CATEGORIES_FAIL: "FETCH_ALL_CATEGORIES_RAIL",
};

export const createCategoryConstants = {
  CREATE_CATEGORY_REQUEST: "CREATE_CATEGORY_REQUEST",
  CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
  CREATE_CATEGORY_FAIL: "CREATE_CATEGORY_RAIL",
};

export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAIL: "GET_ALL_PRODUCT_FAIL",
};

export const productDetailsConstants = {
  GET_PRODUCT_DETAILS_BY_ID_REQUEST: "GET_PRODUCT_DETAILS_BY_ID_REQUEST",
  GET_PRODUCT_DETAILS_BY_ID_SUCCESS: "GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
  GET_PRODUCT_DETAILS_BY_ID_FAIL: "GET_PRODUCT_DETAILS_BY_ID_FAIL",
};

export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
  GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
  GET_ALL_INITIAL_DATA_FAIL: "GET_ALL_INITIAL_DATA_FAIL",
};

export const pageConstants = {
  PAGE_REQUEST: "PAGE_REQUEST",
  PAGE_SUCCESS: "PAGE_SUCCESS",
  PAGE_FAIL: "PAGE_FAIL",
};
export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_CART : "UPDATE_CART",
  ADD_TO_CART_FAIL: "ADD_TO_CART_FAIL",
};
